### ISSUE TITLE
xinput-ui cannot detect touchpad

### ISSUE THREAD

**Issue by tribbloid** [Max-E/xinput-ui#1]
This is the execution result on my laptop screen:

![screenshot](http://imgur.com/Nm7Vlf6.png)

As you can see it fails to detect touchpad, unlike xinput command

**Comment by Max-E** [comment]
I'm afraid the screenshot link in your bug report isn't showing anything for me. Can you figure out how to get the screenshot to me? Also could you make a pastebin or git with the raw output of your xinput command? Thanks.

**Comment by tribbloid** [comment]
OK now fixed, sorry for forgetting the extension

**Comment by Max-E** [comment]
OK, interesting. It looks like there's an extra \t character in the name of the touchpad device, which would probably confuse my parser. Could you copy the xinput output into a pastebin so I have the raw text to work with? Should be a reasonably easy fix.

**Comment by tribbloid** [comment]
aye aye

```
~$ xinput
⎡ Virtual core pointer                        id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳     Touchpad                              id=11   [slave  pointer  (2)]
⎣ Virtual core keyboard                       id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard                 id=5    [slave  keyboard (3)]
    ↳ Power Button                                id=6    [slave  keyboard (3)]
    ↳ Video Bus                                   id=7    [slave  keyboard (3)]
    ↳ Video Bus                                   id=8    [slave  keyboard (3)]
    ↳ Power Button                                id=9    [slave  keyboard (3)]
    ↳ Sleep Button                                id=10   [slave  keyboard (3)]
    ↳ HD WebCam                                   id=12   [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard                id=13   [slave  keyboard (3)]
    ↳ Acer WMI hotkeys                            id=14   [slave  keyboard (3)]
```

**Comment by Max-E** [comment]
Sorry, GitHub's formatting tends to get rid of details like whitespace, could you use some kind of paste service?

**Comment by Max-E** [comment]
Can you try the branch bug1_revised_parser and let me know if it fixes the problem?

**Comment by tribbloid** [comment]
NEGATIVE, OUT

![screenshot](http://i.imgur.com/aD5SeF3.png)

**Comment by Max-E** [comment]
Actually, come to think of it, in either of your screenshots, it doesn't actually look like anything is missing. The touchpad is there with id 11, right after the sleep button.

**Comment by tribbloid** [comment]
Yeah, you are right, I thought the UI can configure values for each 
device, maybe this can be a feature in the next version.

**Comment by Max-E** [comment]
What do you mean by "configure values?"

Are you having any other problems with creating pointers, dragging devices between them, etc? Or should I close this one?

I _did_ find an issue that my branch fixed (creating and then using master pointers with tab characters in their names) so I'm going to apply the branch anyway.

**Comment by tribbloid** [comment]
"configure values" means parsing & editing properties show in command:

```
xinput list-props "{device name}"
```

This not easy task so don't worry, please close this one. Thanks a lot 
for the fix!
